export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <h2>Header</h2>
      <body>{children}</body>
      <h2>Footer</h2>
    </html>
  )
}
